### PR TITLE
Figure out relative path

### PR DESCRIPTION
**Pull request by wk1984**
@mdpiper I moved the path in input and output files; added two variables to indicate the input folder and output folder. If these two lines in a configuration file are blank, the code will try to find input and output files in the same folder with the configuration file. All tests were checked again and passed. Please review these changes. Thanks.

A potential issue is path separator. I used the function "delimiter_detect" to get the separator automatically while I didn't test it in the Windows system yet.

### CODE REVIEW

**Comment by mdpiper** [comment]
@wk1984 Looks good! Thank you for making these changes.

One additional issue: how would you like to handle the `origin_out` directory, used on line 133 of [bmi_main.f90](https://github.com/permamodel/GIPL-BMI-Fortran/blob/master/GIPL/bmi_main.f90)?

**Comment by wk1984** [comment]
@mdpiper That is used to compare with the raw GIPL outputs during my wrapping. These could be removed. I will do it soon.

**Comment by wk1984** [comment]
@mdpiper I moved files and some lines in the code. Seems clean now. Cheers~

**Comment by mdpiper** [comment]
@wk1984 Thanks, Kang! I think we're all set. Would you please merge this PR, then update the version? (I'll use the updated version to build on conda-forge.)

**Pull request merged**
